In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [3]:
df_locations=pd.read_csv('Geospatial_Coordinates.csv')
df_locations.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [6]:
df_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 3 columns):
Postal Code    103 non-null object
Latitude       103 non-null float64
Longitude      103 non-null float64
dtypes: float64(2), object(1)
memory usage: 2.5+ KB

In [5]:
df_postal_codes=pd.read_csv("postal_codes.csv")
df_postal_codes.head()

  Postal Code      Borough                         Neighbourhood
0         M1B  Scarborough                         Rouge,Malvern
1         M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
2         M1E  Scarborough       Guildwood,Morningside,West Hill
3         M1G  Scarborough                                Woburn
4         M1H  Scarborough                             Cedarbrae

In [7]:
df_postal_codes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 3 columns):
Postal Code      103 non-null object
Borough          103 non-null object
Neighbourhood    103 non-null object
dtypes: object(3)
memory usage: 2.5+ KB

In [10]:
df_postal_location=pd.merge(df_locations, df_postal_codes, on='Postal Code')
df_postal_location.head(15)

,Postal Code,Latitude,Longitude,Borough,Neighbourhood
0,M1B,43.806686,-79.194353,Scarborough,"Rouge,Malvern"
1,M1C,43.784535,-79.160497,Scarborough,"Highland Creek,Rouge Hill,Port Union"
2,M1E,43.763573,-79.188711,Scarborough,"Guildwood,Morningside,West Hill"
3,M1G,43.770992,-79.216917,Scarborough,Woburn
4,M1H,43.773136,-79.239476,Scarborough,Cedarbrae
5,M1J,43.744734,-79.239476,Scarborough,Scarborough Village
6,M1K,43.727929,-79.262029,Scarborough,"East Birchmount Park,Ionview,Kennedy Park"
7,M1L,43.711112,-79.284577,Scarborough,"Clairlea,Golden Mile,Oakridge"
8,M1M,43.716316,-79.239476,Scarborough,"Cliffcrest,Cliffside,Scarborough Village West"
9,M1N,43.692657,-79.264848,Scarborough,"Birch Cliff,Cliffside West"
10,M1P,43.757410,-79.273304,Scarborough,"Dorset Park,Scarborough Town Centre,Wexford He..."
11,M1R,43.750072,-79.295849,Scarborough,"Maryvale,Wexford"
12,M1S,43.794200,-79.262029,Scarborough,Agincourt
13,M1T,43.781638,-79.304302,Scarborough,"Clarks Corners,Sullivan,Tam O'Shanter"
14,M1V,43.815252,-79.284577,Scarborough,"Agincourt North,L'Amoreaux East,Milliken,Steel..."